# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('status', models.BooleanField()),
                ('flag', models.CharField(max_length=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('count', models.IntegerField()),
                ('status', models.BooleanField()),
                ('flag', models.CharField(max_length=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('count', models.IntegerField()),
                ('status', models.BooleanField()),
                ('flag', models.CharField(max_length=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
