# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
