# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_goods',
            name='username',
            field=models.CharField(default='zhangyao', max_length=100),
            preserve_default=False,
        ),
    ]
