# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_my_goods_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_goods',
            name='image_url',
            field=models.CharField(default='good/milk.png', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_goods',
            name='image_url',
            field=models.CharField(default='good/milk.png', max_length=200),
            preserve_default=False,
        ),
    ]
