# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_auto_20170602_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('gameround', models.IntegerField()),
                ('flag', models.CharField(max_length=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='my_goods',
            name='gameround',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_goods',
            name='gameid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sign.Game'),
            preserve_default=False,
        ),
    ]
