# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-05 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0006_auto_20170605_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_goods',
            name='gameid',
        ),
        migrations.RemoveField(
            model_name='my_goods',
            name='gameround',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
