# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_auto_20170605_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_goods_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('quality', models.IntegerField()),
                ('count', models.IntegerField()),
                ('status', models.BooleanField()),
                ('username', models.CharField(max_length=100)),
                ('flag', models.CharField(max_length=1)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=200)),
                ('gameround', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='gameid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market_goods',
            name='price_scope',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_goods_history',
            name='gameid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Game'),
        ),
    ]
