# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0011_auto_20170713_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_goods',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_goods_history',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
            preserve_default=False,
        ),
    ]
