# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0012_auto_20170714_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='gameround',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='my_goods',
            name='gameround',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='my_goods_history',
            name='gameround',
            field=models.BigIntegerField(),
        ),
    ]
