# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0013_auto_20170721_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_goods',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
            preserve_default=False,
        ),
    ]
