# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0014_market_goods_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_goods_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('count', models.IntegerField()),
                ('flag', models.CharField(max_length=1)),
                ('status', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('image_url', models.CharField(max_length=200)),
                ('gameround', models.BigIntegerField()),
                ('gameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Game')),
            ],
        ),
    ]
