# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0015_market_goods_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_goods_history',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
